name: CI devops 2022 CPE
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: 
      - main
      - develop
  pull_request:
jobs:
  test-backend:
    runs-on: ubuntu-18.04
    steps:
      #checkout your github code using actions/checkout@v2.3.3
      - uses: actions/checkout@v2.3.3
      #do the same with another action (actions/setup-java@v2) that enable to setup jdk 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      #finally build your app with the latest command
      - name: Build and test with Maven
        working-directory: ./backend/simple-api2
        run: mvn clean verify

  # define job to build and publish docker image
  build-and-push-docker-image:
    needs: test-backend
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest
    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      #Login to dockerhub
      - name: Login to DockerHub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_ACCESS_TOKEN}}
      
      #Build backend image and publish to dockerhub
      - name: Build image and push backend
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code withDockerfile is located
          context: ./backend/simple-api2
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKER_USERNAME}}/simple-api
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      #Build database image and publish to dockerhub
      - name: Build image and push database
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code withDockerfile is located
          context: ./db
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKER_USERNAME}}/db
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      #Build httpd image and publish to dockerhub
      - name: Build image and push httpd
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code withDockerfile is located
          context: ./server
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKER_USERNAME}}/server
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}