name: CI build and push backend on main only
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: 
      - main
  pull_request:
# define job to build and publish docker image
  build-and-push-docker-image-backend:
    needs: test-backend
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest
    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      #Login to dockerhub
      - name: Login to DockerHub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_ACCESS_TOKEN}}
      
      #Build backend image and publish to dockerhub
      - name: Build image and push backend
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code withDockerfile is located
          context: ./backend/simple-api2
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKER_USERNAME}}/backend
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}